import { Course } from './types';

export const COURSES: Course[] = [
  {
    id: 'wb-10',
    title: 'WB Board Class 10 Maths',
    tagline: 'Crack Madhyamik 2026 with 100/100 Strategy',
    description: 'Complete preparation for Madhyamik examination with extensive chapter-wise practice, previous year question analysis, and mock tests.',
    highlight: 'Validity up to final exam',
    pricePlaceholder: '₹4,999',
    category: 'School',
    instructor: 'Raj Sir (15+ Yrs Exp)',
    rating: 4.9,
    reviewsCount: 348,
    difficulty: 'Foundation',
    duration: 'Full Academic Year',
    badge: 'POPULAR CHOICE',
    enrolledCount: 1420,
    featured: true,
    syllabusTopics: ['Algebra & Quadratic Equations', 'Geometry & Circle Theorems', 'Trigonometry Ratios', 'Mensuration 3D & Statistics'],
    posterImage: 'https://images.unsplash.com/photo-1635070041078-e363dbe005cb?auto=format&fit=crop&w=800&q=80'
  },
  {
    id: 'wbjee',
    title: 'WBJEE Full Maths Mastery',
    tagline: 'Target Top Engineering Colleges in West Bengal',
    description: 'Comprehensive competitive preparation for WBJEE engineering aspirants with shortcut techniques, speed drills, and 100+ mock tests.',
    highlight: 'Complete competitive preparation',
    pricePlaceholder: '₹1,999',
    category: 'Competitive',
    instructor: 'Raj Sir & WBJEE Rankers',
    rating: 5.0,
    reviewsCount: 512,
    difficulty: 'Elite Ranker',
    duration: '6 Months Intensive',
    badge: 'BESTSELLER',
    enrolledCount: 2150,
    featured: true,
    syllabusTopics: ['Calculus & Differential Equations', 'Coordinate Geometry & Conic Sections', 'Vectors & 3D Geometry', 'Algebra & Complex Numbers'],
    posterImage: 'https://images.unsplash.com/photo-1509228468518-180dd4864904?auto=format&fit=crop&w=800&q=80'
  },
  {
    id: 'wb-12-s3',
    title: 'WB Board Class 12 (Semester 3)',
    tagline: 'Master HS Higher Mathematics with Precision',
    description: 'Higher secondary mathematics with board exam focus, deep conceptual understanding, and problem-solving shortcuts.',
    highlight: 'HS Part 1 preparation',
    pricePlaceholder: '₹999',
    category: 'School',
    instructor: 'Raj Sir',
    rating: 4.8,
    reviewsCount: 215,
    difficulty: 'Advanced',
    duration: 'Semester-Wise',
    badge: 'NEW PATTERN',
    enrolledCount: 890,
    featured: true,
    syllabusTopics: ['Matrices & Determinants', 'Inverse Trigonometric Functions', 'Continuity & Differentiability', 'Application of Derivatives'],
    posterImage: 'https://images.unsplash.com/photo-1596495578065-6e0763fa1178?auto=format&fit=crop&w=800&q=80'
  },
  {
    id: 'ug-honours',
    title: 'UG Maths Honours (B.Sc)',
    tagline: 'University-Level Pure & Applied Mathematics',
    description: 'University-level mathematics following CBCS pattern. In-depth analysis of Real Analysis, Abstract Algebra, and Linear Algebra.',
    highlight: 'CBCS Pattern',
    pricePlaceholder: '₹5,999',
    category: 'College',
    instructor: 'Raj Sir (M.Sc Gold Medalist)',
    rating: 4.9,
    reviewsCount: 184,
    difficulty: 'Undergraduate',
    duration: 'Full Academic Year',
    badge: 'PREMIUM HONOURS',
    enrolledCount: 640,
    featured: true,
    syllabusTopics: ['Real & Complex Analysis', 'Abstract Algebra & Group Theory', 'Differential Equations & Dynamics', 'Multivariable Calculus'],
    posterImage: 'https://images.unsplash.com/photo-1518133910546-b6c2fb7d79e3?auto=format&fit=crop&w=800&q=80'
  },
  {
    id: 'wb-11-s1',
    title: 'WB Board Class 11 (Semester 1)',
    tagline: 'Solid Foundation for High School Science',
    description: 'Foundation course covering all Semester 1 topics thoroughly with step-by-step problem clearing and regular weekend assessments.',
    highlight: 'Semester-focused approach',
    pricePlaceholder: '₹999',
    category: 'School',
    instructor: 'Raj Sir',
    rating: 4.8,
    reviewsCount: 176,
    difficulty: 'Intermediate',
    duration: 'Semester-Wise',
    badge: 'TRENDING',
    enrolledCount: 780,
    featured: false,
    syllabusTopics: ['Sets, Relations & Functions', 'Trigonometric Functions', 'Principle of Mathematical Induction', 'Complex Numbers'],
    posterImage: 'https://images.unsplash.com/photo-1628155930542-3c7a64e2c833?auto=format&fit=crop&w=800&q=80'
  },
  {
    id: 'wb-11-s2',
    title: 'WB Board Class 11 (Semester 2)',
    tagline: 'Advanced Calculus & Coordinate Geometry',
    description: 'Advanced topics and complete Semester 2 preparation. Prepares students for competitive entrance exam foundations.',
    highlight: 'Semester-focused approach',
    pricePlaceholder: '₹999',
    category: 'School',
    instructor: 'Raj Sir',
    rating: 4.9,
    reviewsCount: 162,
    difficulty: 'Intermediate',
    duration: 'Semester-Wise',
    badge: 'POPULAR',
    enrolledCount: 710,
    featured: false,
    syllabusTopics: ['Linear Inequalities', 'Permutations & Combinations', 'Straight Lines & Conic Sections', 'Limits & Derivatives'],
    posterImage: 'https://images.unsplash.com/photo-1543269865-cbf427effbad?auto=format&fit=crop&w=800&q=80'
  },
  {
    id: 'wb-12-s4',
    title: 'WB Board Class 12 (Semester 4)',
    tagline: 'Final Board Sprint & Revision Series',
    description: 'Final semester preparation for HS examination with full-length test series, answer writing techniques, and doubt resolution.',
    highlight: 'HS Part 2 preparation',
    pricePlaceholder: '₹999',
    category: 'School',
    instructor: 'Raj Sir',
    rating: 4.9,
    reviewsCount: 298,
    difficulty: 'Advanced',
    duration: 'Semester-Wise',
    badge: 'BOARD SPECIAL',
    enrolledCount: 950,
    featured: false,
    syllabusTopics: ['Integrals & Definite Integration', 'Differential Equations', 'Vector Algebra & 3D Geometry', 'Probability & Linear Programming'],
    posterImage: 'https://images.unsplash.com/photo-1523240795612-9a054b0db644?auto=format&fit=crop&w=800&q=80'
  },
  {
    id: 'cbse-5-12',
    title: 'CBSE Class 5 to Class 12',
    tagline: 'NCERT Centric Excellence for All Classes',
    description: 'Dedicated batches for each class following NCERT curriculum with interactive problem solving and Olympiad level challenges.',
    highlight: 'Dedicated batches for each class',
    pricePlaceholder: '₹2,999+',
    category: 'School',
    instructor: 'Senior Math Faculty',
    rating: 4.8,
    reviewsCount: 420,
    difficulty: 'Foundation',
    duration: 'Annual / Flexible',
    badge: 'ALL BATCHES',
    enrolledCount: 1850,
    featured: false,
    syllabusTopics: ['NCERT Concept Clarity', 'Exemplar Problem Solving', 'Board Pattern Worksheets', 'Mental Math & Speed Building'],
    posterImage: 'https://images.unsplash.com/photo-1580582932707-520aed937b7b?auto=format&fit=crop&w=800&q=80'
  }
];

export const CONTACT_INFO = {
  phone: '+91 8345819377',
  email: 'coachingmaathh2002@gmail.com',
  address: 'Kolkata, West Bengal'
};